apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-deployment
  namespace: resume-namespace
  labels:
    app: resume-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: resume-app
  template:
    metadata:
      labels:
        app: resume-app
    spec:
      containers:
      - name: resume-container
        image: banunirahul03/myresume
        ports:
        - containerPort: 8080
