apiVersion: v1
kind: Service
metadata:
  name: resume-service
  namespace: resume-namespace
  labels:
    app: resume-app
spec:
  selector:
    app: resume-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
